#!/bin/bash

suffix='nook.epub'

function shrink
{
	local bkname=$(basename "$1" '.epub')
	local parent=$(pwd)
	unzip -q "$1" -d "/dev/shm/$bkname"
	cd "/dev/shm/$bkname"
	chmod -R 755 ./*
#	optimizing images
	find . -iregex	".*\.\(\(jpe?\|pn\)g\|gif\)"	-type f -print0	| xargs -0 -I {} mogrify -quiet -colorspace Gray -format png -resize '600x800>' {}
	find . -iname	'*.png'				-type f -print0	| xargs -0 -I {} mogrify -quiet -colors 16 -strip -interlace none {}
	find . -iname	'*.png'				-type f -print0	| xargs -0 -I {} optipng -quiet -clobber -fix {}
	find . -iregex	".*\.\(jpe?g\|gif\)"		-type f -print0	| xargs -0 rm -f
	find . -iregex	".*\.x?html?\|\.css"		-type f -print0	| xargs -0 -I {} sed -e 's/\.\(jpe\?g\|gif\)/\.png/Ig'	-i {}
	find . -iname	'*.opf'				-type f -print0	| xargs -0 -I {} sed -e 's/\(jpe\?g\|gif\)/png/Ig'	-i {}
	zip -0 -qX "$parent/$bkname$suffix" ./mimetype
	zip -qrX "$parent/$bkname$suffix" ./* -x mimetype
	cd "$parent"
	rm -rf "/dev/shm/$bkname"
#	java -jar epubcheck-3.0.1/epubcheck-3.0.1.jar "$bkname$suffix"
}

for book in *.epub
do
	shrink "$book"
done
